### ISSUE TITLE
Looks better if it's 0.001

### ISSUE THREAD

**Issue by Ch3ru09** [ZhichGaming/Project-Raphael#12]
https://github.com/ZhichGaming/Project-Raphael/blob/185a653609e272c4478fe0dd87cdad4bf092b329/src/Animation.tsx#L153

**Comment by ZhichGaming** [comment]
Like this? 

https://github.com/ZhichGaming/Project-Raphael/assets/93055907/771e81d1-8baf-49aa-b9b3-183f5cdf199a

Before:

https://github.com/ZhichGaming/Project-Raphael/assets/93055907/80dc57f9-93dd-4d4d-b032-e5649dfca5c3

We could also do halfway.

https://github.com/ZhichGaming/Project-Raphael/assets/93055907/4b2e1faa-ca43-4609-89ff-762f1fc32d27
